# Generic Travis CI Configuration File
# Author: Robert Haschke
sudo: required
dist: trusty
language: generic
compiler:
  - gcc
  - clang

env:
  matrix:
    - ROS_DISTRO="indigo"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu

before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME on $ROS_DISTRO"
  - sudo -E sh -c 'echo "deb $ROS_REPOSITORY_PATH `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-wstool python-catkin-tools
  # Setup rosdep
  - sudo rosdep init
  - rosdep update

install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  # download moveit repos, except $REPOSITORY_NAME
  - cp $TRAVIS_BUILD_DIR/.travis.rosinstall.$ROS_DISTRO .rosinstall
  - wstool rm $REPOSITORY_NAME || true
  - wstool update
  # link in the repo we are testing
  - ln -s $TRAVIS_BUILD_DIR $REPOSITORY_NAME
  - cd ../
  # use rosdep to install all dependencies (including ROS itself)
  - rosdep install --from-paths ./ -i -y --rosdistro $ROS_DISTRO

before_script: # Build the workspace
  - catkin config --extend /opt/ros/$ROS_DISTRO --install --cmake-args -DCMAKE_BUILD_TYPE=Release
  - catkin build --no-status --summarize
  # determine list of packages to test
  - source install/setup.bash
  - TEST_PKGS=$(catkin_topological_order $TRAVIS_BUILD_DIR --only-names)
  - if [ -n "$TEST_PKGS" ]; then TEST_PKGS="--no-deps $TEST_PKGS"; fi
  - if [ "$ALLOW_TEST_FAILURE" != "true" ]; then ALLOW_TEST_FAILURE=false; fi

script: # run tests
  - catkin build --no-status --summarize --make-args tests -- $TEST_PKGS
  # Run tests
  - catkin run_tests --no-status --summarize $TEST_PKGS
  # catkin run_tests always returns 0, use catkin_test_results to check for errors
  # https://github.com/catkin/catkin_tools/issues/245
  - catkin_test_results || $ALLOW_TEST_FAILURE
