sudo: required
services:
  - docker
language: generic

notifications:
  email:
    recipients:
      - rhaschke@techfak.uni-bielefeld.de
env:
  matrix:
    - ROS_DISTRO="kinetic"

before_script:
  - docker pull ros:$ROS_DISTRO-ros-base
script:
  - docker run -v $(pwd):$(pwd) ros:$ROS_DISTRO-ros-base /bin/bash -c "source $(pwd)/.travis.sh"
