# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci.git
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - rhaschke@techfak.uni-bielefeld.de
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros  UPSTREAM_WORKSPACE=.travis.rosinstall

before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
